import os

SECRET_KEY = os.getenv('APP_SECRET_KEY')
SQLALCHEMY_DATABASE_URI = os.getenv('CUSTOM_DB_URL')
PASSWORD_ENCRYPT_KEY = os.getenv('PASSWORD_ENCRYPT_KEY')
SQLALCHEMY_TRACK_MODIFICATIONS = True
