"""empty message

Revision ID: 971a2cb20165
Revises: 89d3638d4469
Create Date: 2021-10-24 23:36:53.455619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971a2cb20165'
down_revision = '89d3638d4469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('permission', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'permission')
    # ### end Alembic commands ###
